#!/bin/sh

set -eu

# See here:
# https://bbs.archlinux.org/viewtopic.php?id=177203

for DEV in "$@"; do
	if grep -q "^$DEV\\b.*\\*enabled" /proc/acpi/wakeup; then
		echo $DEV > /proc/acpi/wakeup
	fi
done
